# Generated by Django 5.1.2 on 2024-10-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_alter_teachers_empid'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
