# Generated by Django 5.1.2 on 2024-10-30 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_schools_dept'),
        ('Teacher', '0003_teachers_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teachers',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='School.schools'),
        ),
    ]
