# Generated by Django 5.1.2 on 2024-10-30 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0005_alter_departments_school'),
        ('School', '0002_schools_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='schools',
            name='dept',
            field=models.ManyToManyField(blank=True, related_name='schools', to='Department.departments'),
        ),
    ]
