# Generated by Django 5.1.2 on 2024-10-30 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('School', '0003_schools_dept'),
        ('Student', '0005_alter_students_dept_alter_students_teacher_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='School.schools'),
        ),
    ]
