# Generated by Django 5.1.2 on 2024-11-01 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_students_school'),
        ('Teacher', '0004_teachers_hod_teachers_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='teacher_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacher.teachers'),
        ),
    ]
