# Generated by Django 5.1.2 on 2024-10-23 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='deptid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
