# Generated by Django 5.1.2 on 2024-10-28 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0003_alter_departments_deptid'),
    ]

    operations = [
        migrations.AddField(
            model_name='departments',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
