# Generated by Django 5.1.2 on 2024-10-30 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0004_departments_is_active'),
        ('School', '0002_schools_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departments',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='School.schools'),
        ),
    ]
