# Generated by Django 5.1.2 on 2024-10-30 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Department', '0005_alter_departments_school'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departments',
            name='hod',
        ),
        migrations.RemoveField(
            model_name='departments',
            name='school',
        ),
    ]
